openapi: 3.0.3
info:
  title: 'Pharmachine API Doc'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/all-users:
    get:
      summary: ''
      operationId: getApiAllUsers
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: Admin
                    email: admin@gmail.com
                    role: admin
                    email_verified_at: null
                    created_at: '2024-01-05T08:40:06.000000Z'
                    updated_at: '2024-01-05T08:40:06.000000Z'
                  -
                    id: 2
                    name: 'Alexa Mcneil'
                    email: employee@gmail.com
                    role: worker
                    email_verified_at: null
                    created_at: '2024-01-10T08:54:11.000000Z'
                    updated_at: '2024-01-10T08:54:11.000000Z'
                  -
                    id: 3
                    name: 'Paloma Mooney'
                    email: xadeje@mailinator.com
                    role: worker
                    email_verified_at: null
                    created_at: '2024-01-10T08:54:30.000000Z'
                    updated_at: '2024-01-10T08:54:30.000000Z'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
